export const filters = {
  condition: ["Excellent", "Good", "Fair"],
  category: [
    "College Books (Higher Education Textbooks)",
    "Exam/Test Preparation Books",
    "Reading Books (Novels, Children, Business, Literature, History, etc.)",
    "School Books (up to 12th)",
  ],
  classType: [
    "B.Tech",
    "B.Sc",
    "B.Com",
    "BCA",
    "MBA",
    "M.Tech",
    "M.Sc",
    "Ph.D",
    "12th",
    "11th",
    "10th",
    "9th",
    "8th",
    "7th",
    "6th",
    "5th",
  ],
  brand: [
    { id: 1, name: "B.Tech" },
    { id: 2, name: "M.Tech" },
    { id: 3, name: "MBA" },
    { id: 4, name: "BBA" },
    { id: 5, name: "B.Sc" },
    { id: 6, name: "M.Sc" },
    { id: 7, name: "PhD" },
  ],
  gender: [
    { _id: "Men", name: "Men" },
    { _id: "Women", name: "Women" },
    { _id: "Boys", name: "Boys" },
    { _id: "Girls", name: "Girls" },
    { _id: "Unisex", name: "Unisex" },
  ],
  color: [
    { id: 1, name: "Red" },
    { id: 2, name: "Green" },
    { id: 3, name: "Yellow" },
    { id: 4, name: "Blue" },
    { id: 5, name: "Gyay" },
  ],

};